# Generated by Django 4.0.1 on 2022-01-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('excerpt', models.TextField()),
                ('img', models.URLField()),
                ('date', models.DateField(auto_now_add=True)),
                ('slug', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Post details',
            },
        ),
    ]
